/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockjournal;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bradl
 */
public class FinancialTable extends javax.swing.JFrame {

    private Stock stock;
    private AutoStock autostock;

    public FinancialTable() {
        initComponents();
        String currentDirectory = System.getProperty("user.dir");
        currentDirectory.replace("'\'", "\\");
        File catalog = new File(currentDirectory + "\\catalog.txt");
        String records = new String(readFromFile(catalog.getPath(), 0, (int) catalog.length()));
        Scanner reader = new Scanner(records);
        reader.useDelimiter("[|\n]");

        ArrayList<String> names = new ArrayList<>();
        while (reader.hasNext()) {
            //only include the stock names
            names.add(reader.next());
            reader.next();
            reader.next();
        }

        ArrayList<AutoStock> stocks = new ArrayList<>();
        //get all objects from local files in the form of autostocks
        for (String name : names) {
            try {
                File source = new File(currentDirectory + "\\" + name + ".txt");
                ObjectInputStream is = new ObjectInputStream(new FileInputStream(source.getPath()));
                try {
                    stock = (Stock) is.readObject();
                    is.close();
                    if (stock.isAuto()) {
                        autostock = (AutoStock) stock;
                    } else if (!stock.isAuto()) {
                        autostock.setStockName(stock.getStockName());
                        autostock.setTicker(stock.getTicker());
                        autostock.setExchange(stock.getExchange());
                        autostock.setNpm(stock.getNpm());
                        autostock.setCurrentratio(stock.getCurrentratio());
                    }
                } catch (ClassNotFoundException e) {
                    e.printStackTrace();
                }
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }
            stocks.add(autostock);
            stock = new Stock();
            autostock = new AutoStock();
        }
        
        for (AutoStock stock : stocks) {
            System.out.println(stock.getStockName());
        }
        
        DefaultTableModel model = (DefaultTableModel) financialsTable.getModel();
        Object rowData[] = new Object[9];

        for (AutoStock stock : stocks) {
            rowData[0] = stock.getStockName();
            rowData[1] = stock.getTicker();
            rowData[2] = stock.getExchange();
            rowData[3] = stock.getNpm();
            rowData[4] = stock.getCurrentratio();
            rowData[5] = stock.getPe();
            rowData[6] = stock.getRoe();
            rowData[7] = stock.getBeta();
            rowData[8] = stock.getDividend();

            model.addRow(rowData);
            rowData = new Object[9];
        }
    }

    private static byte[] readFromFile(String file, int pos, int size) {
        RandomAccessFile target;
        try {
            target = new RandomAccessFile(file, "r"); //"r" means for reading purposes.
            target.seek(pos);
            byte[] bytesToRead = new byte[size];
            target.read(bytesToRead);
            target.close();
            return bytesToRead;
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return new byte[0];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        financialsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        financialsReturnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        financialsTable.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        financialsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock Name", "Ticker", "Exchange", "NPM", "Current Ratio", "P/E Ratio", "ROE%", "Dividend Yield%", "Beta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        financialsTable.setRowHeight(20);
        jScrollPane1.setViewportView(financialsTable);
        if (financialsTable.getColumnModel().getColumnCount() > 0) {
            financialsTable.getColumnModel().getColumn(2).setResizable(false);
            financialsTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setText("Financials");

        financialsReturnButton.setBackground(new java.awt.Color(100, 100, 100));
        financialsReturnButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        financialsReturnButton.setForeground(new java.awt.Color(255, 255, 255));
        financialsReturnButton.setText("Return to Home Page");
        financialsReturnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                financialsReturnButtonMouseClicked(evt);
            }
        });
        financialsReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financialsReturnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(financialsReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(financialsReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void financialsReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financialsReturnButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_financialsReturnButtonActionPerformed

    private void financialsReturnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_financialsReturnButtonMouseClicked
        setVisible(false);
        dispose();
    }//GEN-LAST:event_financialsReturnButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinancialTable.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinancialTable.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinancialTable.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinancialTable.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinancialTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton financialsReturnButton;
    private javax.swing.JTable financialsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
