/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockjournal;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bradl
 */
public class HomePage extends javax.swing.JFrame {

    public HomePage() {
        initComponents();
        populateStockTable();
    }

    public void populateStockTable() {
        //create or locate catalog file in user's local drive
        String currentDirectory = System.getProperty("user.dir");
        currentDirectory.replace("'\'", "\\");
        File catalog = new File(currentDirectory + "\\catalog.txt");

        //read data from catalog file
        ArrayList<String> records = new ArrayList<>();
        String delimiter = "[|\n]";
        records = readRecordsFromCatalog(records, catalog, delimiter);

        //populate stock table with data from catalog file
        DefaultTableModel model = (DefaultTableModel) stockTable.getModel();
        Object rowData[] = new Object[3];
        for (int i = 0; i < records.size(); i += 3) {
            rowData[0] = records.get(i);
            rowData[1] = records.get(i + 1);
            rowData[2] = records.get(i + 2);
            model.addRow(rowData);
            rowData = new Object[3];
        }
    }

    private static ArrayList<String> readRecordsFromCatalog(ArrayList<String> records, File file, String delimiter) {
        try {
            Scanner reader = new Scanner(file);
            reader.useDelimiter(delimiter);

            while (reader.hasNext()) {
                String s = reader.next();
                records.add(s);
            }
            reader.close();
            return records;
        } catch (FileNotFoundException e) {
            System.out.println("Error: file not found.");
            return records;
        }
    }

    private static void removeRecord(String file, String term) {
        String temp = "temp.txt";
        File oldFile = new File(file);
        File newFile = new File(temp);
        String Name = "";
        String Ticker = "";
        String Exchange = "";

        try {
            FileWriter fw = new FileWriter(temp, true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            Scanner reader = new Scanner(new File(file));
            reader.useDelimiter("[|\n]"); //identifying splitting signals

            while (reader.hasNext()) {
                Name = reader.next();
                Ticker = reader.next();
                Exchange = reader.next();
                if (!Name.equals(term)) { //while the removal target isn't scanned 
                    pw.println(Name + "|" + Ticker + "|" + Exchange);
                }
            }
            reader.close();
            pw.flush();
            pw.close();
            oldFile.delete();
            File dump = new File(file);
            newFile.renameTo(dump); //sequence to write data into new file and replace the old one

        } catch (IOException e) {
            System.out.println("Error.");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newEntryButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        stockTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        viewEntriesButton = new javax.swing.JButton();
        viewFinancialsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        removeEntryButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(16, 16, 16));

        newEntryButton.setBackground(new java.awt.Color(100, 100, 100));
        newEntryButton.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        newEntryButton.setForeground(new java.awt.Color(255, 255, 255));
        newEntryButton.setText("New Entry");
        newEntryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newEntryButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newEntryButtonMouseEntered(evt);
            }
        });
        newEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEntryButtonActionPerformed(evt);
            }
        });

        stockTable.setBackground(new java.awt.Color(250, 250, 250));
        stockTable.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));
        stockTable.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        stockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Ticker", "Exchange"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stockTable.setToolTipText("");
        stockTable.setRowHeight(24);
        jScrollPane1.setViewportView(stockTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setText("Stock Journal");

        viewEntriesButton.setBackground(new java.awt.Color(100, 100, 100));
        viewEntriesButton.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        viewEntriesButton.setForeground(new java.awt.Color(255, 255, 255));
        viewEntriesButton.setText("View Entry");
        viewEntriesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewEntriesButtonMouseClicked(evt);
            }
        });
        viewEntriesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEntriesButtonActionPerformed(evt);
            }
        });

        viewFinancialsButton.setBackground(new java.awt.Color(100, 100, 100));
        viewFinancialsButton.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        viewFinancialsButton.setForeground(new java.awt.Color(255, 255, 255));
        viewFinancialsButton.setText("View Financials");
        viewFinancialsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewFinancialsButtonMouseClicked(evt);
            }
        });
        viewFinancialsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFinancialsButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(100, 100, 100));
        exitButton.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit Program");
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        removeEntryButton.setBackground(new java.awt.Color(100, 100, 100));
        removeEntryButton.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        removeEntryButton.setForeground(new java.awt.Color(255, 255, 255));
        removeEntryButton.setText("Remove Entry");
        removeEntryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeEntryButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeEntryButtonMouseEntered(evt);
            }
        });
        removeEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEntryButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setText("Real-time market movements and your notes, all in one.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewFinancialsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewEntriesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newEntryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeEntryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewEntriesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewFinancialsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newEntryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeEntryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEntryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newEntryButtonActionPerformed

    private void newEntryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newEntryButtonMouseClicked
        new NewStockPage().setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_newEntryButtonMouseClicked

    private void viewEntriesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewEntriesButtonMouseClicked
        int row = stockTable.getSelectedRow();
        if (row == -1) {
            HighlightDialog dialog = new HighlightDialog(this, true);
            dialog.setLocation(700, 400);
            dialog.setVisible(true);
        } else {
            new JournalPage(stockTable.getModel().getValueAt(stockTable.getSelectedRow(), 0).toString(), stockTable.getModel().getValueAt(stockTable.getSelectedRow(), 1).toString()).setVisible(true);
        }
    }//GEN-LAST:event_viewEntriesButtonMouseClicked

    private void viewEntriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEntriesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewEntriesButtonActionPerformed

    private void viewFinancialsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewFinancialsButtonMouseClicked
        new FinancialTable().setVisible(true);
    }//GEN-LAST:event_viewFinancialsButtonMouseClicked

    private void viewFinancialsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFinancialsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewFinancialsButtonActionPerformed

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    private void newEntryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newEntryButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_newEntryButtonMouseEntered

    private void removeEntryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeEntryButtonMouseClicked
        int row = stockTable.getSelectedRow();
        if (row == -1) {
            HighlightDialog dialog = new HighlightDialog(this, true);
            dialog.setLocation(700, 400);
            dialog.setVisible(true);
        } else {

            DefaultTableModel model = (DefaultTableModel) stockTable.getModel();

            if (stockTable.getSelectedRowCount() == 1) {

                //delete the corresponding record from catalog file
                String currentDirectory = System.getProperty("user.dir");
                currentDirectory.replace("'\'", "\\");
                File catalog = new File(currentDirectory + "\\catalog.txt");
                removeRecord(catalog.getPath(), model.getValueAt(stockTable.getSelectedRow(), 0).toString());
                File fileToRemove = new File(currentDirectory + "\\" + model.getValueAt(stockTable.getSelectedRow(), 0).toString() + ".txt");
                fileToRemove.delete();

                //remove the selected row
                model.removeRow(stockTable.getSelectedRow());

            } else {
                TooManyRowsSelectedDialog dialog = new TooManyRowsSelectedDialog(this, true);
                dialog.setLocation(700, 400);
                dialog.setVisible(true);
            }

            
            HomePage home = new HomePage();
            setVisible(false);
            home.setVisible(true);
            dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_removeEntryButtonMouseClicked

    private void removeEntryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeEntryButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_removeEntryButtonMouseEntered

    private void removeEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEntryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeEntryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newEntryButton;
    private javax.swing.JButton removeEntryButton;
    private javax.swing.JTable stockTable;
    private javax.swing.JButton viewEntriesButton;
    private javax.swing.JButton viewFinancialsButton;
    // End of variables declaration//GEN-END:variables
}
