/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockjournal;

import com.google.gson.Gson;
import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author bradl
 */
public class NewStockPage extends javax.swing.JFrame {

    private String stockname = " ";
    private boolean auto = false;
    private String ticker = " ";
    private String exchange = " ";
    private String npm = " ";
    private String currentratio = " ";

    /**
     * Creates new form NewStockPage
     */
    public NewStockPage() {
        initComponents();
    }

    private static void writeToFile(String file, String data, int pos) throws IOException {
        RandomAccessFile target = new RandomAccessFile(file, "rw"); //"rw" refers to read & write operations
        target.seek(pos);
        target.write(data.getBytes()); //getBytes method converts data to bytes
        target.close();
    }

    private ArrayList<String> getLiveFinancials(String ticker) {
        ArrayList<String> results = new ArrayList<>();
        try {
            //establish connection with CNBC web API
            URL url = new URL("https://quote.cnbc.com/quote-html-webservice/restQuote/symbolType/symbol?symbols=" + ticker + "&output=json");
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("GET");

            con.setRequestProperty("Content-Type", "application/json");
            con.setRequestProperty("accept", "*/*");

            int status = con.getResponseCode();

            BufferedReader in = new BufferedReader(
                    new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuffer content = new StringBuffer();
            while ((inputLine = in.readLine()) != null) {
                content.append(inputLine);
            }
            in.close();

            //Deserializing with help from gson library
            String result = (content.toString());
            Gson gson = new Gson();
            Response deserialized = gson.fromJson(result, Response.class);

            results.add(deserialized.getFormattedQuoteResult().getFormattedQuote().get(0).getLast());
            results.add(deserialized.getFormattedQuoteResult().getFormattedQuote().get(0).getPe());
            results.add(deserialized.getFormattedQuoteResult().getFormattedQuote().get(0).getROETTM());
            results.add(deserialized.getFormattedQuoteResult().getFormattedQuote().get(0).getBeta());
            results.add(deserialized.getFormattedQuoteResult().getFormattedQuote().get(0).getDividendyield());

        } catch (MalformedURLException e) {
            return new ArrayList<String>();
        } catch (IOException e) {
            return new ArrayList<String>();
        }
        return results;
    }

    public static double getValue(Pattern pattern, String query) {
        Matcher matcher = pattern.matcher(query);
        if (matcher.find()) {
            double result = Double.parseDouble(matcher.group(1));
            return result;
        }
        return -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newEntry = new javax.swing.JLabel();
        financialmetrics1 = new javax.swing.JLabel();
        financialmetrics3 = new javax.swing.JLabel();
        financialmetrics4 = new javax.swing.JLabel();
        saveNewStockButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        newStockNameField = new javax.swing.JTextField();
        newTickerField = new javax.swing.JTextField();
        autoButton = new javax.swing.JButton();
        manualButton = new javax.swing.JButton();
        financialmetrics5 = new javax.swing.JLabel();
        financialmetrics2 = new javax.swing.JLabel();
        financialmetrics6 = new javax.swing.JLabel();
        financialmetrics7 = new javax.swing.JLabel();
        newExchangeField = new javax.swing.JTextField();
        newNpmField = new javax.swing.JTextField();
        newCurrentRatioField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newEntry.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        newEntry.setText("New Stock Entry");

        financialmetrics1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        financialmetrics1.setText("Stock Name: ");

        financialmetrics3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        financialmetrics3.setText("Ticker:");

        financialmetrics4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        financialmetrics4.setText("Auto-generate share price and advanced financials?");

        saveNewStockButton.setBackground(new java.awt.Color(100, 100, 100));
        saveNewStockButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        saveNewStockButton.setForeground(new java.awt.Color(255, 255, 255));
        saveNewStockButton.setText("Save");
        saveNewStockButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveNewStockButtonMouseClicked(evt);
            }
        });
        saveNewStockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewStockButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(100, 100, 100));
        cancelButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        newStockNameField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        newStockNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStockNameFieldActionPerformed(evt);
            }
        });

        newTickerField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        newTickerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTickerFieldActionPerformed(evt);
            }
        });

        autoButton.setBackground(new java.awt.Color(100, 100, 100));
        autoButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        autoButton.setForeground(new java.awt.Color(255, 255, 255));
        autoButton.setText("Yes");
        autoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autoButtonMouseClicked(evt);
            }
        });
        autoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoButtonActionPerformed(evt);
            }
        });

        manualButton.setBackground(new java.awt.Color(100, 100, 100));
        manualButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        manualButton.setForeground(new java.awt.Color(255, 255, 255));
        manualButton.setText("No");
        manualButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manualButtonMouseClicked(evt);
            }
        });
        manualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualButtonActionPerformed(evt);
            }
        });

        financialmetrics5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        financialmetrics5.setText("Optional Information:");

        financialmetrics2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        financialmetrics2.setText("Exchange:");

        financialmetrics6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        financialmetrics6.setText("Net Profit Margin% (NPM):");

        financialmetrics7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        financialmetrics7.setText("Current Ratio:");

        newExchangeField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        newExchangeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newExchangeFieldActionPerformed(evt);
            }
        });

        newNpmField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        newNpmField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newNpmFieldActionPerformed(evt);
            }
        });

        newCurrentRatioField.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        newCurrentRatioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCurrentRatioFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(financialmetrics5)
                                .addComponent(newEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(financialmetrics1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(newStockNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(financialmetrics3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(newTickerField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(financialmetrics7, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(newCurrentRatioField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(financialmetrics6, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(newNpmField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(financialmetrics2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(162, 162, 162)
                                        .addComponent(newExchangeField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(financialmetrics4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                                .addComponent(autoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(manualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveNewStockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(newEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(financialmetrics1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newStockNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(financialmetrics3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newTickerField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(financialmetrics4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(autoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(financialmetrics5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(financialmetrics2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newExchangeField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(financialmetrics6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newNpmField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(financialmetrics7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCurrentRatioField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveNewStockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveNewStockButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveNewStockButtonMouseClicked

        stockname = newStockNameField.getText();
        ticker = newTickerField.getText();
        exchange = newExchangeField.getText();
        npm = newNpmField.getText();
        currentratio = newCurrentRatioField.getText();

        String currentDirectory = System.getProperty("user.dir");
        currentDirectory.replace("'\'", "\\");

        //checking if a stock object with the same name already exists as a file
        if (new File(currentDirectory + "\\" + stockname + ".txt").exists()) {
            StockAlreadyExistsDialog dialog = new StockAlreadyExistsDialog(this, true);
            dialog.setLocation(700, 400);
            dialog.setVisible(true);

        } else {

            if (stockname.isEmpty() || ticker.isEmpty()) {
                FieldsEmptyDialog dialog = new FieldsEmptyDialog(this, true);
                dialog.setLocation(700, 400);
                dialog.setVisible(true);

            } else {

                Stock newStock = new Stock(stockname, false, ticker, exchange, npm, currentratio);
                AutoStock newAutoStock = new AutoStock(stockname, true, ticker, exchange, npm, currentratio);

                //creating a new stock/autostock object based on user's choice
                String stockFileName = currentDirectory + "\\" + stockname + ".txt";

                try {
                    ObjectOutputStream os = new ObjectOutputStream(new FileOutputStream(stockFileName));
                    if (auto) {
                        ArrayList<String> financials = getLiveFinancials(ticker);
                        newAutoStock.setPrice(financials.get(0));
                        newAutoStock.setPe(financials.get(1));
                        newAutoStock.setRoe(financials.get(2));
                        newAutoStock.setBeta(financials.get(3));
                        newAutoStock.setDividend(financials.get(4));
                        os.writeObject(newAutoStock);

                    } else {
                        os.writeObject(newStock);
                    }
                    os.close();

                    //opening or creating the catalog file
                    File catalog = new File(currentDirectory + "\\catalog.txt");

                    try {
                        String delimiter = "|";
                        String message = stockname + delimiter + ticker + delimiter + exchange + "\n";
                        writeToFile(catalog.getPath(), message, (int) catalog.length());

                        SaveDialog dialog = new SaveDialog(this, true);
                        dialog.setLocation(700, 400);
                        dialog.setVisible(true);
                        setVisible(false);
                        HomePage home = new HomePage();
                        home.setVisible(true);
                        dispose();

                    } catch (IOException e) {
                        e.printStackTrace();
                    }

                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }

        }


    }//GEN-LAST:event_saveNewStockButtonMouseClicked

    private void saveNewStockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNewStockButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveNewStockButtonActionPerformed

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        setVisible(false);
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void newStockNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStockNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newStockNameFieldActionPerformed

    private void newTickerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTickerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newTickerFieldActionPerformed

    private void autoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autoButtonMouseClicked
        auto = true;
    }//GEN-LAST:event_autoButtonMouseClicked

    private void autoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoButtonActionPerformed

    private void manualButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manualButtonMouseClicked
        auto = false;
    }//GEN-LAST:event_manualButtonMouseClicked

    private void manualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manualButtonActionPerformed

    private void newExchangeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newExchangeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newExchangeFieldActionPerformed

    private void newNpmFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newNpmFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newNpmFieldActionPerformed

    private void newCurrentRatioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCurrentRatioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCurrentRatioFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStockPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStockPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStockPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStockPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStockPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autoButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel financialmetrics1;
    private javax.swing.JLabel financialmetrics2;
    private javax.swing.JLabel financialmetrics3;
    private javax.swing.JLabel financialmetrics4;
    private javax.swing.JLabel financialmetrics5;
    private javax.swing.JLabel financialmetrics6;
    private javax.swing.JLabel financialmetrics7;
    private javax.swing.JButton manualButton;
    private javax.swing.JTextField newCurrentRatioField;
    private javax.swing.JLabel newEntry;
    private javax.swing.JTextField newExchangeField;
    private javax.swing.JTextField newNpmField;
    private javax.swing.JTextField newStockNameField;
    private javax.swing.JTextField newTickerField;
    private javax.swing.JButton saveNewStockButton;
    // End of variables declaration//GEN-END:variables
}
